# numpy入门教程

In [2]:
# 引入numpy
import numpy as np
import matplotlib.pyplot as plt

## 创建一个数组

In [3]:
# 一维数组
a = np.array([0, 1, 2, 3, 4])
b = np.array((0, 1, 2, 3, 4))
c = np.arange(5)
d = np.linspace(0, 2*np.pi, 5) # 从0到2PI之间取5个数，均匀取
e = np.random.rand(5)
f = np.random.randn(5)

print(a) 
print(b) 
print(c) 
print(d) 
print(e) 
print(f) 
print(a[3]) 

[0 1 2 3 4]
[0 1 2 3 4]
[0 1 2 3 4]
[0.         1.57079633 3.14159265 4.71238898 6.28318531]
[0.33667066 0.73297659 0.19567331 0.79863498 0.43639544]
[-0.73143327  1.18395604  1.38478388  1.05672664 -0.33106573]
3


In [ ]:
# 二维数组
a1 = np.array([[11, 12, 13, 14, 15],
              [16, 17, 18, 19, 20],
              [21, 22, 23, 24, 25],
              [26, 27, 28 ,29, 30],
              [31, 32, 33, 34, 35]]) # 从已有的二维列表生成
b1 = np.random.randint(0, 100, (5, 5)) # 从0到100之间的随机整数生成5x5的二维数组 
c1 = np.random.random((5, 5))*100

print(a1) # >>>25
print(b1)
print(c1)
print(d[::2])

In [ ]:
# 多维数组的切片
print(a1[0, :3]) # 第1行1至3列
print(a1[0:3, 3]) # 第4列1至3行
print(a1[0:3, 0:3]) # 截取第1至3行中1至3列
print(a1[::2, ::2]) # 截取单行单列

基本操作符
只是能够从数组中创建和检索元素和属性不能满足你的需求，你有时也需要对它们进行数学运算。 你完全可以使用四则运算符 +、- 、/ 来完成运算操作。


In [ ]:
a = np.arange(25)
a = a.reshape((5, 5))

b = np.array([10, 62, 1, 14, 2, 56, 79, 2, 1, 45,
              4, 92, 5, 55, 63, 43, 35, 6, 53, 24,
              56, 3, 56, 44, 78])
b = b.reshape((5,5))
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a ** 2)
print(a < b) 
print(a > b)

print(a.dot(b))

除了 `dot()` 之外，这些操作符都是对数组进行逐元素运算。比如 `(a, b, c) + (d, e, f)` 的结果就是 `(a+d, b+e, c+f)` 。
它将分别对每一个元素进行配对，然后对它们进行运算。它返回的结果是一个数组。注意，当使用逻辑运算符比如 “<” 和 “>” 的时候，返回的将是一个布尔型数组，这点有一个很好的用处，后边我们会提到。

`dot()` 函数计算两个数组的点积。它返回的是一个标量（只有大小没有方向的一个值）而不是数组。

In [ ]:
a2 = np.linspace(0, 2 * np.pi, 50)
b2 = np.sin(a2)

plt.plot(a2, b2)

mask = b2 > 0
plt.plot(a2[mask], b2[mask], 'bo')
mask = (b2 >= 0) & (a2 <= np.pi / 2)
plt.plot(a2[mask], b2[mask], 'go')

In [ ]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')
sepal_length = np.genfromtxt(url,delimiter=',',dtype='float',usecols=[0])

In [ ]:
print(sepal_length)
print(iris[:4])
print(iris[:4, 4])

In [ ]:
# 创建包含5到10之间随机浮动的二维数组
np.set_printoptions(precision=3)
np.random.uniform(5,10,(5,5))

In [ ]:
a = np.random.random((3,3))/1e3
np.set_printoptions(precision=6,suppress=True)
a

In [ ]:
x = np.array([1,2,3,4,5,6,7,8,9])
mu, med, sd = np.mean(x), np.median(x), np.std(x)
print(mu, med, sd)

In [18]:
points = np.arange(3)
print(points.mean())
print(np.meshgrid(points, points.T))


1.0
[array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]]), array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2]])]
